name: fordward_app
description: A new Flutter project.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.5
  firebase_auth: ^4.17.6
  google_maps_flutter: ^2.5.0
  geolocator: ^7.6.2
  flip_card: ^0.5.0

  english_words: ^4.0.0
  provider: ^6.0.0
  cloud_firestore: ^4.15.6

  google_maps_flutter: ^2.5.0
  geolocator: ^7.6.2
  google_place: ^0.4.0
  flip_card: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
